# Generated by Django 3.2.4 on 2021-06-09 04:37

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='novel_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='novel',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 9, 4, 37, 59, 68158, tzinfo=utc), verbose_name='date released'),
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_name', models.CharField(default='', max_length=255)),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novels.novel')),
            ],
            options={
                'ordering': ('id',),
                'unique_together': {('novel', 'chapter_name')},
            },
        ),
    ]
