# Generated by Django 3.2.4 on 2021-06-19 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0004_auto_20210612_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='Story',
        ),
    ]
