# Generated by Django 3.2.4 on 2021-07-13 05:42

from django.conf import settings
from django.db import migrations, models
import novels.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('novels', '0006_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='novel',
            options={'ordering': ('id',)},
        ),
        migrations.AlterField(
            model_name='comment',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=models.SET(novels.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
    ]
